// This file is generated by Prismic local builder. Update with care!

export { default as Image } from './Image'
export { default as LandingPage } from './LandingPage'
export { default as SpecialText } from './SpecialText'
export { default as TextBlock } from './TextBlock'
